# Generated by Django 5.2 on 2025-05-06 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='fiest_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='employer',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/covers/'),
        ),
        migrations.AddField(
            model_name='employer',
            name='culture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='founded_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='locations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/logos/'),
        ),
        migrations.AddField(
            model_name='employer',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='open_positions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employer',
            name='profile_completeness',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employer',
            name='team_members',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=50)),
                ('experience_level', models.CharField(max_length=50)),
                ('salary_range', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('responsibilities', models.TextField()),
                ('benefits', models.TextField(blank=True, null=True)),
                ('skills', models.JSONField(default=list)),
                ('remote', models.BooleanField(default=False)),
                ('urgent', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.employer')),
            ],
        ),
    ]
