# Generated by Django 5.2 on 2025-05-11 06:34

import api.models.employer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_fiest_name_jobseeker_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='open_positions',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='team_members',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='employer',
            name='_locations',
            field=models.TextField(blank=True, db_column='locations', null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='_team_members',
            field=models.TextField(blank=True, db_column='team_members', null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='education',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='experience',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='profile_completeness',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employer',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.employer.employer_cover_path),
        ),
        migrations.AlterField(
            model_name='employer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.employer.employer_logo_path),
        ),
    ]
