# Generated by Django 5.2 on 2025-05-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_resumeprofileview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeprofileview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
